export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_ALL_DECKS_OF_USER_START = "FETCH_ALL_DECKS_OF_USER_START";
export const FETCH_ALL_DECKS_OF_USER_SUCCESS = "FETCH_ALL_DECKS_OF_USER_SUCCESS";
export const FETCH_ALL_DECKS_OF_USER_FAILURE = "FETCH_ALL_DECKS_OF_USER_FAILURE";

export const FETCH_CURRENT_DECK_START = "FETCH_CURRENT_DECK_START";
export const FETCH_CURRENT_DECK_SUCCESS = "FETCH_CURRENT_DECK_SUCCESS";
export const FETCH_CURRENT_DECK_FAILURE = "FETCH_CURRENT_DECK_FAILURE";

export const FETCH_NEXT_CARD_POOL_START = "FETCH_NEXT_CARD_POOL_START";
export const FETCH_NEXT_CARD_POOL_SUCCESS = "FETCH_NEXT_CARD_POOL_SUCCESS";
export const FETCH_NEXT_CARD_POOL_FAILURE = "FETCH_NEXT_CARD_POOL_FAILURE";

export const DECREMENT_CARD_START = "DECREMENT_CARD_START";
export const DECREMENT_CARD_SUCCESS = "DECREMENT_CARD_SUCCESS";
export const DECREMENT_CARD_FAILURE = "DECREMENT_CARD_FAILURE";

export const REMOVE_CARD_START = "REMOVE_CARD_START";
export const REMOVE_CARD_SUCCESS = "REMOVE_CARD_SUCCESS";
export const REMOVE_CARD_FAILURE = "REMOVE_CARD_FAILURE";

export const ADD_NEW_CARD_START = "ADD_NEW_CARD_START";
export const ADD_NEW_CARD_SUCCESS = "ADD_NEW_CARD_SUCCESS";
export const ADD_NEW_CARD_FAILURE = "ADD_NEW_CARD_FAILURE";

export const INCREMENT_CARD_START = "INCREMENT_CARD_START";
export const INCREMENT_CARD_SUCCESS = "INCREMENT_CARD_SUCCESS";
export const INCREMENT_CARD_FAILURE = "INCREMENT_CARD_FAILURE";

export const ADD_NEW_DECK_START = "ADD_NEW_DECK_START"
export const ADD_NEW_DECK_SUCCESS = "ADD_NEW_DECK_SUCCESS"
export const ADD_NEW_DECK_FAILURE = "ADD_NEW_DECK_FAILURE"

export const SET_DECKLIST_ID = "SET_DECKLIST_ID";
