version: "3.2"
services:
  server_flask:
    build: ./server_flask
    ports:
      - "3000:5000"
    environment:
      FLASK_APP: app
      FLASK_HOST: "0.0.0.0"
      FLASK_ENV: "Development"
      FLASK_PORT: 5000
      FLASK_DEBUG: 1
